name: 'Test JS actions stuff'
description: 'Test JS actions stuff'
inputs:
  with-docker:
    description: 'If true this action will also build the package in the requested docker-images'
    required: true
    default: false
  docker-images:
    description: 'If with-docker is true then extra packages are built for these images'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
