name: Test Boost.Stacktrace

on:
  push:
    paths:
      - ".github/workflows/boost-stacktrace.yml"
      - "test-boost-stacktrace/*"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: gcc
        build-type: RelWithDebInfo
        ubuntu: |
          apt: libboost-stacktrace-dev
        macos: |
          brew: boost
    - name: Show Boost libraries
      if: matrix.os == 'macos-latest'
      run: |
        ls /usr/local/lib/libboost_*
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: gcc
        build-type: RelWithDebInfo
        project-dir: test-boost-stacktrace
    - name: Show main
      if: matrix.os == 'windows-latest'
      run: |
        C:/devel/install/bin/main.exe
