name: clang?
on: push

jobs:
  Ubuntu_16_04:
    runs-on: ubuntu-16.04
    steps:
      - name: Show me clang
        run: |
          dpkg -l | grep clang || echo "No clang stuff installed"
          dpkg -l | grep llvm || echo "No llvm stuff installed"
          sudo apt-get install -y cython cython3 python-nose python3-nose python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev doxygen doxygen-latex libboost-all-dev gfortran
