name: clang-format?
on: push

jobs:
  Ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
      - name: Show me clang-format
        run: |
          dpkg -l | grep clang || echo "No clang stuff installed"
          sudo apt-get update
          sudo apt-get remove clang-6.0 libllvm6
          sudo apt-get install clang-format-6.0
          clang-format --version
