name: docker buildx?
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /etc/docker/daemon.json || echo "No /etc/docker/daemon.json"
          docker --version
          DOCKER_CLI_EXPERIMENTAL=enabled docker --help
          docker buildx --help
