name: docker build package
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        set -x
        mkdir -p /tmp/package
        mkdir -p /tmp/packages-bionic-amd64
        cd /tmp/package && git clone --recursive https://github.com/jrl-umi3218/Eigen3ToPython
        docker run -d -v /tmp/package/Eigen3ToPython:/package -v /tmp/packages-bionic-amd64:/out --name builder --privileged -t ubuntu:18.04 /bin/bash
        docker exec builder apt-get update -qq
        docker exec builder apt-get install -qq devscripts build-essential equivs
        docker exec builder mk-build-deps -i -r -t "apt-get -y" /package/debian/control
        docker exec -w /package builder sed -i -e's/quilt/native' debian/source/format
        docker exec -w /package builder dpkg-buildpackage -us -uc
        docker exec builder ls /
        docker exec builder bash -c "mv /*.deb /out"
        ls /tmp/packages-bionic-amd64
    - uses: actions/upload-artifact@v1
      with:
        name: packages-bionic-amd64
        path: /tmp/packages-bionic-amd64/
