name: Test stuff with Docker actions
on: push

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./test-docker-action
      env:
        dist: '18.04'
      with:
        dist: '18.04'
