name: docker buildx?
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Show me clang
        run: |
          cat /etc/docker/daemon.json || echo "No /etc/docker/daemon.json"
          DOCKER_CLI_EXPERIMENTAL=enabled docker --help
