name: docker build package
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        set -x
        mkdir -p /tmp/package
        mkdir -p /tmp/packages-bionic-amd64
        cd /tmp/package && git clone --recursive https://github.com/jrl-umi3218/Eigen3ToPython
        docker run -d -v /tmp/package/:/package --name builder --privileged -t gergondet/pbuilder:bionic-amd64 /bin/bash
        docker exec -w /package/Eigen3ToPython builder mk-build-deps -i -r -t "apt-get -y" debian/control
        docker exec -w /package/Eigen3ToPython builder debuild --no-tgz-check -i -I -b -us -uc
        docker exec builder ls /package
        ls /tmp/package
        mv /tmp/package/*.deb /tmp/packages-bionic-amd64
        ls /tmp/packages-bionic-amd64
    - uses: actions/upload-artifact@v1
      with:
        name: packages-bionic-amd64
        path: /tmp/packages-bionic-amd64/
