name: Download Boost with Powershell

on:
  push:
    paths:
      - ".github/workflows/get-boost.yml"

jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Boost - With Retry
      shell: pwsh
      continue-on-error: true
      run: |
        function DownloadFileWithRetry
        {
          param(
            [Parameter(Mandatory = $true)]
            $Url,
            [Parameter(Mandatory = $true)]
            $Out,
            [ValidateNotNullOrEmpty()]
            $MaxTry=10
          )
          $Try = 1
          while($Try -le $MaxTry)
          {
            if($Try -ne 1)
            {
              Write-Host "Download failed, try $Try out of $MaxTry"
            }
            try
            {
              (New-Object System.Net.WebClient).DownloadFile($Url, $Out)
              break
            }
            catch
            {
              if(Test-Path $Out)
              {
                Remove-Item $Out
              }
              $Try++
            }
          }
          if(Test-Path $Out)
          {
            Write-Host "Download succeeded after $Try tries"
            Get-FileHash $Out | Format-List
            Remove-Item $Out
          }
        }
        $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.77.0/boost_1_77_0-msvc-14.2-64.exe"
        $Out = "$env:TEMP\boost.exe"
        $DownloadI = 0
        while($DownloadI -le 10)
        {
          Write-Host "Download $DownloadI out of 10"
          DownloadFileWithRetry -Url "$Url" -Out "$Out"
          $DownloadI++
        }
