name: Test stuff with git
on: push

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Try to push
      if: github.ref == 'refs/heads/master'
      run: |
        set -x
        cd $GITHUB_WORKSPACE
        cat .git/config
        git config --global user.name "JRL/IDH Continuous Integration Tool"
        git config --global user.email "jrl-idh+ci@gmail.com"
        git checkout -b test
        git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository}} test:test
