name: Test stuff with git
on: push

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Try to push
      if: github.ref == 'refs/heads/master'
      run: |
        set -x
        git config --global http.extraheader 'AUTHORIZATION: Bearer ${{ secrets.GITHUB_TOKEN }}'
        git config --global user.name "JRL/IDH Continuous Integration Tool"
        git config --global user.email "jrl-idh+ci@gmail.com"
        cd $GITHUB_WORKSPACE
        git checkout -b test
        git push --force origin test:test
