name: Test stuff in git

on:
  push:
    paths:
      - ".github/workflows/git.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Test git status
        run: |
          set -e
          set -x
          git ls-files
