name: Test stuff in git

on:
  push:
    paths:
      - ".github/workflows/git.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Test git status
        run: |
          set -e
          set -x
          pwd
          cd $GITHUB_WORKSPACE
          pwd
          git status
          git ls-files
