name: Investigate ExternalProject_Add issue on macOS

on:
  push:
    paths:
      - '.github/workflows/macos-external-project.yml'
      - 'test-macos-external-project/*'
jobs:
  one:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run
        shell: bash
        run: |
          mkdir -p ${TMPDIR-/tmp}/build
          cmake -S ${GITHUB_WORKSPACE} -B ${TMPDIR-/tmp}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVERBOSE_TEST_OUTPUT=ON -DMC_RTC_SUPERBUILD_VERBOSE=ON
