name: Check pkg-config installation with brew

on:
  push:
    paths:
      - '.github/workflows/macos-brew-pkg-config.yml'
      - 'macos-brew-pkg-config/*'

jobs:
  one:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clear environment (script)
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          compiler: gcc
          build-type: RelWithDebInfo
      - name: Check
        shell: bash
        run: |
          which pkg-config
          export INSTALL_PREFIX=/usr/local
          export PYTHON_VERSION=`python3 -c 'import sys; print("{}.{}".format(sys.version_info.major, sys.version_info.minor))'`
          export PATH=$INSTALL_PREFIX/bin:$PATH
          export LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
          export DYLD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$DYLD_LIBRARY_PATH
          export PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
          export PYTHONPATH=$INSTALL_PREFIX/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH
          which pkg-config
          brew install pkg-config
          pkg-config --version
          #export BREW_DEPENDENCIES="coreutils pkg-config gnu-sed wget python cmake doxygen libtool tinyxml2 geos boost eigen nanomsg yaml-cpp qt qwt pyqt gcc spdlog ninja libnotify"
          #brew update
          #brew install $BREW_DEPENDENCIES
          #brew upgrade $BREW_DEPENDENCIES
          cmake -P macos-brew-pkg-config/test.cmake
          cmake -P macos-brew-pkg-config/test2.cmake
