name: Check pkg-config installation with brew

on:
  push:
    paths:
      - '.github/workflows/macos-brew-pkg-config.yml'
      - 'macos-brew-pkg-config/*'

jobs:
  one:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clear environment (script)
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          compiler: gcc
          build-type: RelWithDebInfo
      - name: Check
        shell: bash
        run: |
          brew install pkg-config
          pkg-config --version
          export BREW_DEPENDENCIES="coreutils pkg-config gnu-sed wget python cmake doxygen libtool tinyxml2 geos boost eigen nanomsg yaml-cpp qt qwt pyqt gcc spdlog ninja libnotify"
          brew update
          brew install $BREW_DEPENDENCIES
          brew upgrade $BREW_DEPENDENCIES
          cmake -P macos-brew-pkg-config/test.cmake
