name: Investigate ExternalProject_Add issue on macOS

on:
  push:
    paths:
      - '.github/workflows/macos-external-project.yml'
      - 'test-macos-external-project/*'
jobs:
  one:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Env
        shell: bash
        run: |
          env
      - name: Build and run
        shell: bash
        run: |
          mkdir -p ${TMPDIR-/tmp}/build
          cmake -S ${GITHUB_WORKSPACE}/test-macos-external-project -B ${TMPDIR-/tmp}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVERBOSE_TEST_OUTPUT=ON -DMC_RTC_SUPERBUILD_VERBOSE=ON
