name: Check pkg-config installation with brew

on:
  push:
    paths:
      - '.github/workflows/macos-brew-pkg-config.yml'
      - 'macos-brew-pkg-config/*'

jobs:
  one:
    runs-on: macos-latest
    steps:
      - name: Clear environment (script)
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          compiler: gcc
          build-type: RelWithDebInfo
      - name: Before
        shell: bash
        run: |
          echo "PATH: ${PATH}"
          echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
          echo "DYLD_LIBRARY_PATH: ${DYLD_LIBRARY_PATH}"
          echo "PKG_CONFIG_PATH: ${PKG_CONFIG_PATH}"
          echo "PYTHONPATH: ${PYTHONPATH}"
          which pkg-config
          echo "otool -L pkg-config"
          otool -L /usr/local/bin/pkg-config
          pkg-config --version
      - name: Brew upgrade
        shell: bash
        run: |
          brew upgrade
      - name: Brew doctor
        shell: bash
        run: |
          brew doctor
      - name: After
        shell: bash
        run: |
          export INSTALL_PREFIX=/usr/local
          export PYTHON_VERSION=`python3 -c 'import sys; print("{}.{}".format(sys.version_info.major, sys.version_info.minor))'`
          export PATH=$INSTALL_PREFIX/bin:$PATH
          export LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
          export DYLD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$DYLD_LIBRARY_PATH
          export PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
          export PYTHONPATH=$INSTALL_PREFIX/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH
          echo "PATH: ${PATH}"
          echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
          echo "DYLD_LIBRARY_PATH: ${DYLD_LIBRARY_PATH}"
          echo "PKG_CONFIG_PATH: ${PKG_CONFIG_PATH}"
          echo "PYTHONPATH: ${PYTHONPATH}"
          which pkg-config
          echo "otool -L pkg-config"
          otool -L /usr/local/bin/pkg-config
          pkg-config --version
