name: Python3 on macOS?

on:
  push:
    paths:
      - ".github/workflows/python3.yml"
      - "python3/CMakeLists.txt"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Brew dependencies
        shell: bash
        run: |
          set -e
          set -x
          sudo xcode-select -switch /Applications/Xcode_11.7.app
          brew update || true
          brew install eigen boost tinyxml2 geos nanomsg yaml-cpp pkg-config libtool gcc || true
          brew upgrade eigen boost tinyxml2 geos nanomsg yaml-cpp pkg-config libtool gcc || true
      - name: Check python3/pip3 on command line
        shell: bash
        run: |
          set -e
          set -x
          which pip3
          pip3 --version
          sudo pip3 install cython coverage nose numpy
          which python3
          python3 --version
          python3 -c "import cython"
          cd python3
          python3 test.py
          cd ../
      - name: Simple project
        shell: bash
        run: |
          set -e
          set -x
          cd python3 && mkdir build && cd build
          cmake ../
          make
          #      - name: Eigen3ToPython
          #        shell: bash
          #        run: |
          #          set -e
          #          set -x
          #          cd
          #          git clone --recursive https://github.com/jrl-umi3218/Eigen3ToPython
          #          cd Eigen3ToPython
          #          mkdir build
          #          cd build
          #          cmake ../ -DPYTHON_BINDING_FORCE_PYTHON3=ON
          #          make
          #          make install
