name: Python in Windows?

on:
  push:
    paths:
      - ".github/workflows/python.yml"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Check python status
        shell: bash
        run: |
          set -e
          set -x
          python --version || true
          python3 --version || true
          pip --version || true
          pip3 --version || true
