name: Python3 on macOS?

on:
  push:
    paths:
      - ".github/workflows/python3.yml"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Try install cython
        shell: bash
        run: |
          set -e
          set -x
          which pip3
          pip3 --version
          sudo pip3 install cython
          which python3
          python3 --version
          python3 -c "import cython"
          echo ""
