name: QWT with brew?

on: push

jobs:

  qwt-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        brew install qt5 qwt
    - name: Headers?
      run: |
        set -x
        ls /usr/local/opt/qwt/lib/qwt.framework/Headers
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        export PATH=/usr/local/opt/qt/bin:$PATH
        export CMAKE_PREFIX_PATH=/usr/local/opt/qt:$CMAKE_PREFIX_PATH
        cmake ../
        make VERBOSE=1
        otool -L main
        ./main

  qwt-xenial:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        sudo apt-get install -y libqwt-qt5-dev qt5-default
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        cmake ../
        make
        ldd main
        ./main

  qwt-bionic:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        sudo apt-get install -y libqwt-qt5-dev qt5-default
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        cmake ../
        make
        ldd main
        ./main
