name: QWT with brew?

on: push

jobs:

  qwt-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        brew install qwt
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        cmake ../
        make
        otool -L main
        ./main

  qwt-xenial:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        sudo apt-get install -y libqwt-qt5-dev
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        cmake ../
        make
        ldd main
        ./main

  qwt-bionic:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        sudo apt-get install -y libqwt-qt5-dev
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        cmake ../
        make
        ldd main
        ./main
