name: QWT with brew?

on: push

jobs:

  qwt:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        set -x
        brew install qwt
        mkdir build
        cd build
        cmake ../
