name: QWT with brew?

on: push

jobs:

  qwt:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Qwt
      run: |
        set -x
        brew install qwt
    - name: Build
      run: |
        set -x
        mkdir build
        cd build
        cmake ../
