# This is a reusable workflow

on:
  workflow_call:
    inputs:
      dist:
        required: false
        default: '["bionic", "focal"]'
        type: string
      arch:
        required: false
        default: '["i386", "amd64"]'
        type: string
      exclude:
        required: false
        default: '[{"dist": "focal", "arch": "i386"}]'
        type: string
jobs:
  build-it:
    strategy:
      matrix:
        dist: ${{ fromJson(inputs.dist)}}
        arch: ${{ fromJson(inputs.arch)}}
      exclude: ${{ fromJson(inputs.exclude) }}
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        run: |
          echo "Run for ${{ matrix.dist}}/${{ matrix.arch }}"
