# This is a reusable workflow

on:
  workflow_call:
    inputs:
      matrix:
        required: false
        type: string
        default: |
          {
            "dist": ["bionic", "focal", "jammy"],
            "arch": ["i386", "amd64"],
            "exclude":
            [
              {"dist": "focal", "arch": "i386" },
              {"dist": "jammy", "arch": "i386" },
            ]
          }
      deps:
        required: false
        default: ''
        type: string
      dist:
        required: false
        default: '["bionic", "focal"]'
        type: string
      arch:
        required: false
        default: '["i386", "amd64"]'
        type: string
      exclude:
        required: false
        default: '[{"dist": "focal", "arch": "i386"}]'
        type: string
jobs:
  build-it:
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        run: |
          echo "Run for ${{ matrix.dist}}/${{ matrix.arch }}"
  trigger-deps:
    if: ${{ inputs.deps != '' }}
    strategy:
      matrix:
        dep: ${{ fromJson(inputs.deps) }}
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        run: |
          echo "Trigger ${{ matrix.dep }}"
