name: Try stuff on Linux CI

on:
  push:
    paths:
      - '.github/workflows/test-linux.yml'
jobs:
  one:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test stuff
        run: |
          set -e
          set -x
          git submodule add https://github.com/jrl-umi3218/jrl-cmakemodules python/cmake
          ./run_unit_tests.sh
