name: Try stuff on Windows CI

on:
  push:
    paths:
      - '.github/workflows/test-windows.yml'
jobs:
  one:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test stuff
        run: |
          python3 -m site --user-base
          python3 -m pip uninstall pre-commit
          python3 -m pip install --user pre-commit
