name: Test JS action

on:
  push:
    paths:
      - ".github/workflows/test-action.yml"
      - "test-js-action/**"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Non-empty list
      uses: ./test-js-action
      with:
        with-docker: ${{ matrix.os == 'ubuntu-18.04' }}
        docker-images: '[debian:buster, ubuntu:20.04]'
    - name: Empty list
      uses: ./test-js-action
      with:
        with-docker: ${{ matrix.os == 'ubuntu-16.04' }}
