name: Test JS action

on:
  push:
    paths:
      - ".github/workflows/test-action.yml"
      - "test-js-action/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./test-js-action
      with:
        with-docker: true
        docker-images: '[debian:buster, ubuntu:20.04]'
