on:
  push:
    paths:
      - '.github/workflows/test-reusable-workflow.yml'
      - '.github/workflows/reusable-workflow.yml'

jobs:
  doit:
    uses: gergondet/test-github-actions/.github/workflows/reusable-workflow.yml@master
    with:
      deps: '["jrl-umi3218/SpaceVecAlg", "jrl-umi3218/RBDyn"]'
