name: Test triggers

on:
  repository_dispatch:
    types: [trigger-master, trigger-release]
  push:
    paths:
      - '.github/workflows/trigger.yml'
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: 'Hello from trigger-master'
        run: |
          echo 'Hello from trigger-master'
        if: github.event.action == 'trigger-master'
      - name: 'Hello from trigger-release'
        run: |
          echo 'Hello from trigger-release'
        if: github.event.action == 'trigger-release'
      - name: 'Hello from master'
        run: |
          echo 'Hello from master'
        if: github.event.action == null && github.ref == 'refs/heads/master'
      - name: 'Hello from other'
        run: |
          echo 'Hello from other'
        if: github.event.action == null && github.ref != 'refs/heads/master'
