name: Try setting environment variables from powershell

on:
  push:
    paths:
      - '.github/workflows/windows-env.yml'
      - 'windows-env/*'
jobs:
  one:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set a variable from CMake
        run: |
          echo "====Before===="
          cat $env:GITHUB_ENV
          cmake -B windows-env/build -S windows-env
          echo "====After===="
          cat $env:GITHUB_ENV
      - name: Show environment
        run: |
          cmake -E environment
