name: Run Xvfb to record video

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          set -e
          set -x
          sudo apt-get update -qq
          sudo apt-get install -qq xvfb ffmpeg mesa-utils fluxbox
      - name: Setup xvfb and run application
        run: |
          Xvfb :1 -screen 0 1920x1080x24 &
          fluxbox &
          sleep 10s
          glxgears &
          GLXGEARS_PID=$!
          sleep 5s
          mkdir -p /tmp/video
          ffmpeg -y -f x11grab -video_size 1920x1080 -i :1 /tmp/video/xvfb.mp4 -codec:v libx264 -r 12 -pix_fmt yuv420p /tmp/video/xvfb.mp4 &
          FFMPEG_PID=$!
          sleep 10s
          kill -2 $FFMPEG_PID
          kill -9 $GLXGEARS_PID
          sleep 5s
      - name: Upload video
        uses: actions/upload-artifact@v1
        with:
          name: video
          path: /tmp/video
