name: Run Xvfb to record video

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          set -e
          set -x
          sudo apt-get update -qq
          sudo apt-get install -qq xvfb ffmpeg mesa-utils fluxbox xserver-xorg xserver-xorg-core xserver-xorg-video-all libwayland-egl1-mesa
      - name: Setup xvfb and run application
        run: |
          export DISPLAY=":1"
          Xvfb $DISPLAY -screen 0 1920x1080x24 &
          sleep 10s
          fluxbox &
          sleep 10s
          glxgears &
          GLXGEARS_PID=$!
          sleep 5s
          mkdir -p /tmp/video
          ffmpeg -y -f x11grab -framerate 25 -video_size cif -i $DISPLAY /tmp/video/xvfb.mpg &
          FFMPEG_PID=$!
          sleep 10s
          kill -2 $FFMPEG_PID
          sleep 5s
      - name: Upload video
        uses: actions/upload-artifact@v1
        with:
          name: video
          path: /tmp/video
